name: pytorch-lightning
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch==2.0.0
  - pytorch-cuda==11.7
  - pytorch-lightning==2.0.0
  - torchmetrics=0.11.4
  - torchvision==0.15.0
  - ipykernel==6.21.3
  - jupyter==1.0.0
  - matplotlib==3.7.1
  - pandas==1.5.3
  - numpy==1.24.2
  - tqdm==4.65.0
  - tensorboard==2.12.0
  - pip:
      - python-graphviz==0.20.1
